#!/bin/bash -l

#SBATCH -J compro_spu
#SBATCH -o compro_spu_%j.txt
#SBATCH -e compro_spu_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mem=32G
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=10:00:00


cd ~/community_profiling_sputum/

conda activate qiime2-2021.4


out_dir="/dartfs-hpc/scratch/f002bx6/qiime_out"

qiime feature-table summarize \
  --i-table $out_dir/16S-table-dada2.qza \
  --o-visualization $out_dir/table.qzv \
  --m-sample-metadata-file metadata.tsv

qiime feature-table tabulate-seqs \
  --i-data $out_dir/16S-rep-seqs-dada2.qza \
  --o-visualization $out_dir/rep-seqs.qzv

qiime alignment mafft \
  --i-sequences $out_dir/16S-rep-seqs-dada2.qza \
  --o-alignment $out_dir/aligned-rep-seqs.qza

qiime alignment mask \
  --i-alignment $out_dir/aligned-rep-seqs.qza \
  --o-masked-alignment $out_dir/masked-aligned-rep-seqs.qza


qiime phylogeny fasttree \
  --i-alignment $out_dir/masked-aligned-rep-seqs.qza \
  --o-tree $out_dir/unrooted-tree.qza

qiime phylogeny midpoint-root \
  --i-tree $out_dir/unrooted-tree.qza \
  --o-rooted-tree $out_dir/rooted-tree.qza

qiime tools export \
  --input-path $out_dir/rooted-tree.qza \
  --output-path $out_dir/exported-tree  





